### ISSUE TITLE
aiaccel does not work with abci because the version of sqlite is old.

### ISSUE THREAD

**Issue by koba-22** [aistairc/aiaccel#235]
Describe the bug
~~~
aiaccel does not work with abci because the version of sqlite is old.
It worked locally.
The reason why abci's sqlite version is old is unknown.
log etc below.
---

sqliteのバージョンが古いためabciでaiaccelが動かない。
localでは動いた。
abciのsqliteのバージョンが古い理由は不明。
logなどを以下に。
---
~~~
Additional context
~~~
abci - python 3.8.13 - sqlite 3.7.17
-
ssh abci
cd work-main-test
source /etc/profile.d/modules.sh
module load gcc/11.2.0
module load python/3.8/3.8.13
source venv/bin/activate
(venv) abci$ python
Python 3.8.13 (default, Apr  6 2022, 07:25:12)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'
---

abci - python 3.10.4 - sqlite 3.7.17
-
ssh abci
cd work-main-test-python10
source /etc/profile.d/modules.sh
module load gcc/11.2.0
module load python/3.10/3.10.4
source venv/bin/activate
(venv) abci$ python
Python 3.10.4 (main, Apr  8 2022, 10:31:54) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.7.17'
---

local - python 3.9.2 - sqlite 3.34.1
-
ssh local
python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.34.1'
---

log for follow-up
-
version below
commit c1394b1e019736aa77c23b22ea1ad79527eb6ac7 (HEAD -> main, origin/main, origin/HEAD)
Date:   Wed Feb 15 19:40:52 2023 +0900
-
Last error message below
sqlalchemy.exc.NotSupportedError: (sqlite3.NotSupportedError) deterministic=True requires SQLite 3.8.3 or higher
(Background on this error at: https://sqlalche.me/e/20/tw8g)
-
ssh abci
qrsh -g group-name -l rt_C.small=1 -l h_rt=5:00:00
mkdir work-main-test
cd work-main-test
source /etc/profile.d/modules.sh
module load gcc/11.2.0
module load python/3.8/3.8.13
python3 -m venv venv
source venv/bin/activate
export PYTHONPATH=
echo $PYTHONPATH
git clone https://github.com/aistairc/aiaccel.git
cd aiaccel
git log
commit c1394b1e019736aa77c23b22ea1ad79527eb6ac7 (HEAD -> main, origin/main, origin/HEAD)
Date:   Wed Feb 15 19:40:52 2023 +0900
-
python -m pip install --upgrade pip
pip install -r requirements.txt
python setup.py install
cp -r examples/sphere ..
cd ../sphere
python -m aiaccel.cli.start --config config.yaml --clean
Cleaning workspace
Workspace directory ~/work-main-test/sphere/work is cleaned.
config: ~/work-main-test/sphere/config.yaml
Traceback (most recent call last):
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
    return self.pool.connect()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1270, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 917, in __connect
    pool.dispatch.connect.for_modify(
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 718, in on_connect
    do_on_connect(dbapi_connection)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 567, in connect
    fn(conn)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 550, in set_regexp
    dbapi_connection.create_function(
sqlite3.NotSupportedError: deterministic=True requires SQLite 3.8.3 or higher

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/apps/centos7/python/3.8.13_gcc11.2.0/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/apps/centos7/python/3.8.13_gcc11.2.0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/cli/start.py", line 104, in <module>
    main()
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/cli/start.py", line 61, in main
    modules = [Master(vars(args)), Optimizer(vars(args)), Scheduler(vars(args))]
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/master/abstract_master.py", line 44, in __init__
    super().__init__(self.options)
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/module.py", line 87, in __init__
    self.storage = Storage(self.ws)
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/storage/storage.py", line 21, in __init__
    self.trial = Trial(db_path)
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/storage/trial.py", line 13, in __init__
    super().__init__(file_name)
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/util/retry.py", line 20, in _wrapper
    raise e
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/util/retry.py", line 17, in _wrapper
    return func(*args, **kwargs)
  File "~/work-main-test/venv/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/storage/abstract.py", line 26, in __init__
    Base.metadata.create_all(self.engine)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 5576, in create_all
    bind._run_ddl_visitor(
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3219, in _run_ddl_visitor
    with self.begin() as conn:
  File "/apps/centos7/python/3.8.13_gcc11.2.0/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3209, in begin
    with self.connect() as conn:
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in connect
    return self._connection_cls(self)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2410, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3269, in raw_connection
    return self.pool.connect()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 455, in connect
    return _ConnectionFairy._checkout(self)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 1270, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 719, in checkout
    rec = pool._do_get()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 283, in _do_get
    return self._create_connection()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 396, in _create_connection
    return _ConnectionRecord(self)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 681, in __init__
    self.__connect()
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 917, in __connect
    pool.dispatch.connect.for_modify(
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 473, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 487, in __call__
    fn(*args, **kw)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 718, in on_connect
    do_on_connect(dbapi_connection)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 567, in connect
    fn(conn)
  File "~/work-main-test/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 550, in set_regexp
    dbapi_connection.create_function(
sqlalchemy.exc.NotSupportedError: (sqlite3.NotSupportedError) deterministic=True requires SQLite 3.8.3 or higher
(Background on this error at: https://sqlalche.me/e/20/tw8g)
---
~~~

**Comment by KanaiYuma-aist** [comment]
恐らく https://github.com/aistairc/aiaccel/issues/233 と同様のissueだと思います。
こちらの方が詳しく書かれているようなので、https://github.com/aistairc/aiaccel/issues/233 の方をclose しておきます。

**Comment by KanaiYuma-aist** [comment]
なお、#233 の方にも書いてありますが、02/17に確認した限りでは
コミット 9732c325e626ae70c18bf31b9b2ca1803f1955eb で発生し、それ以前のコミットでは`sqlalchemy.exc.NotSupportedError`は発生しませんでした。

**Comment by koba-22** [comment]
ご指摘ありがとうございます。
重複、失礼しました。

**Comment by koba-22** [comment]
Temporary workaround using singularity.
(singularityを使用した一時的な対応方法。)

References
https://docs.abci.ai/ja/containers/

~~~
ssh abci
qrsh -g group-name -l rt_C.small=1 -l h_rt=5:00:00
mkdir work-main-test-debian
cd work-main-test-debian
~~~
I want to minimize singularity sif files.
~~~
git clone https://github.com/aistairc/aiaccel.git
cd aiaccel
git log
commit c1394b1e019736aa77c23b22ea1ad79527eb6ac7
Date:   Wed Feb 15 19:40:52 2023 +0900
~~~
Create debian.cif.
~~~
cd ~/work-main-test-debian
module load singularitypro
vi debian.def
Bootstrap: docker
From: debian

%post
    apt update
    apt upgrade -y
    apt install -y python3-pip python3-venv

%runscript
    /bin/bash
-
singularity build --fakeroot debian.sif debian.def
~~~
run debian.sif
~~~
singularity run debian.sif
Singularity> python3 -V
Python 3.9.2
Singularity> python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.34.1'
>>> exit()
~~~
run aiaccel
~~~
python3 -m venv venv
source venv/bin/activate
export PYTHONPATH=
echo $PYTHONPATH
cd aiaccel
python -m pip install --upgrade pip
pip install -r requirements.txt
python setup.py install
cp -r examples/sphere ..
cd ../sphere
python -m aiaccel.cli.start --config config.yaml --clean
(omit log)
Master    INFO     Master finished.
Optimizer INFO     Optimizer delete alive file.
Optimizer INFO     Optimizer finished.
Scheduler INFO     Scheduler finished.
moving...
Best result    : results/20230220_113037/result/000004.hp
               : 9.966180279652084
Total time [s] : 170
Done.
~~~
