### ISSUE TITLE
TPE resumption is not working

### ISSUE THREAD

**Issue by aramoto99** [aistairc/aiaccel#30]
While fixing the CI test (#28) of the TPE resume function, an unexpected error occurred. I think it might be a bug. The error message was as follows. 

```
Process Process-1:
Traceback (most recent call last):
  File "/home/member/opt/working/env/Python-3.8.7/Lib/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/member/opt/working/env/Python-3.8.7/Lib/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/member/opt/working/new_opt/my/env/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/module.py", line 364, in start
    self.pre_process()
  File "/home/member/opt/working/new_opt/my/env/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/optimizer/tpe/search.py", line 35, in pre_process
    super().pre_process()
  File "/home/member/opt/working/new_opt/my/env/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/optimizer/abstract_optimizer.py", line 168, in pre_process
    super().pre_process()
  File "/home/member/opt/working/new_opt/my/env/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/module.py", line 344, in pre_process
    self.resume()
  File "/home/member/opt/working/new_opt/my/env/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/module.py", line 647, in resume
    self._deserialize(self.snapshot.process_memory_objects)
  File "/home/member/opt/working/new_opt/my/env/lib/python3.8/site-packages/aiaccel-0.0.1-py3.8.egg/aiaccel/optimizer/tpe/search.py", line 247, in _deserialize
    raise ()
TypeError: exceptions must derive from BaseException

```

<hr>

 config.yaml
```
generic:
  workspace: "./work"
  job_command: "python user.py"
  batch_job_timeout: 600

resource:
  type: "local"
  num_node: 4

ABCI:
  group: "[group]"
  job_script_preamble: "./job_script_preamble.sh"
  job_execution_options: ""

optimize:
  search_algorithm: "tpe"
  goal: "minimize"
  trial_number: 30
  rand_seed: 42
  parameters:
    -
      name: "x1"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
      initial: 1.0
    -
      name: "x2"
      type: "uniform_float"
      lower: 0.0
      upper: 5.0
      initial: 1.0
```
<hr>
<b> Steps to error.</b>

1.  Optimize examples/benchmark
> python -m aiaccel.start --config config.yml --clean

2. Stops the process in mid-process

3. resume
> python -m aiaccel.start --config config.yaml --resume 6

**Comment by KanaiYuma-aist** [comment]
When the TPE optimization is resumed, the following code reads the hp file in `work/hp/running`.

https://github.com/aistairc/aiaccel/blob/57667308a2f30eb605e000eb0ef84dd0cf47c05c/aiaccel/optimizer/tpe/search.py#L222-L247

If the file does not exist in `work/hp/running`, proceed below `else` and a TypeError occurs.

It seems that hp files do or do not exist in `work/hp/running` depending on when hp.yaml is saved in the state directory.

---

TPE最適化をresumeした際、下記コードで `work/hp/running` 内のhpファイルを読み込んでいます。

`work/hp/running` 内にファイルが存在しない場合、`else`以下に進んでTypeErrorが発生します。

stateディレクトリに hp.yaml を保存したタイミング次第で `work/hp/running` 内にhpファイルが存在したりしなかったりするようです。
